services:
  app:
    container_name: bank
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www
    restart: always
    depends_on:
     - php

  php:
    container_name: php-bank
    build:
      args:
        user: USER
        uid: 1000
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www

  db:
    container_name: db-bank
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "bank"
    volumes:
      - ./docker/mysql:/var/lib/mysql

  phpmyadmin:
    container_name: bank-admin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=8084

  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass "root"
    volumes:
      - ./docker/redis:/data
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD="root"
